flags: {}
packages:
- '.'
resolver: lts-12.25
extra-deps: []

allow-newer: true

nix:
  # Not using pure here because it is very practical to inherit
  # $NVIM_LISTEN_ADDRESS when developing and debugging plugins.
  pure: false

  packages:
  - zlib
  - neovim # for api generation
